package kagacraft.main;

import net.minecraft.item.ItemStack;
import net.minecraft.src.ModLoader;
import cpw.mods.fml.common.registry.LanguageRegistry;

public class KagacraftNameTable 
{

	public static void registers()
	{
		addName(Atoms.addStack(Atoms.HYDROGEN), "Hydrogen");
		addName(Atoms.addStack(Atoms.HELIUM), "Helium");
		addName(Atoms.addStack(Atoms.LITHIUM), "Lithium");
		addName(Atoms.addStack(Atoms.BERYLLIUM), "Beryllium");
		addName(Atoms.addStack(Atoms.BORON), "Boron");
		addName(Atoms.addStack(Atoms.CARBON), "Carbon");
		addName(Atoms.addStack(Atoms.NITROGEN), "Nitrogen");
		addName(Atoms.addStack(Atoms.OXYGEN), "Oxygen");
		addName(Atoms.addStack(Atoms.FLUORINE), "Fluorine");
		addName(Atoms.addStack(Atoms.NEON), "Neon");
		addName(Atoms.addStack(Atoms.SODIUM), "Sodium");
		addName(Atoms.addStack(Atoms.MAGNESIUM), "Magnesium");
		addName(Atoms.addStack(Atoms.ALMINIUM), "Alminium");
		addName(Atoms.addStack(Atoms.SILICON), "Silicon");
		addName(Atoms.addStack(Atoms.PHOSPHORUS), "Phosphorus");
		addName(Atoms.addStack(Atoms.SULFUR), "Sulfur");
		addName(Atoms.addStack(Atoms.CHLORINE), "Chlorine");
		addName(Atoms.addStack(Atoms.ARGON), "Argon");
		addName(Atoms.addStack(Atoms.POTASSIUM), "Potassium");
		addName(Atoms.addStack(Atoms.CALCIUM), "Calcium");
		addName(Atoms.addStack(Atoms.SCANDIUM), "Scandium");
		addName(Atoms.addStack(Atoms.TITANIUM), "Titanium");
		addName(Atoms.addStack(Atoms.VANADIUM), "Vanadium");
		addName(Atoms.addStack(Atoms.CHROMIUM), "Chromium");
		addName(Atoms.addStack(Atoms.MANGANESE), "Managanese");
		addName(Atoms.addStack(Atoms.IRON), "Iron");
		addName(Atoms.addStack(Atoms.COBALT), "Cobalt");
		addName(Atoms.addStack(Atoms.NICKEL), "Nickel");
		addName(Atoms.addStack(Atoms.COPPER), "Copper");
		addName(Atoms.addStack(Atoms.ZINC), "Zinc");
		addName(Atoms.addStack(Atoms.GALLIUM), "Gallium");
		addName(Atoms.addStack(Atoms.GERMANIUM), "Garmanium");
		addName(Atoms.addStack(Atoms.ARSENIC), "Arsenic");
		addName(Atoms.addStack(Atoms.SELENIUM), "Selemium");
		addName(Atoms.addStack(Atoms.BROMINE), "Bromine");
		addName(Atoms.addStack(Atoms.KRYPTON), "Krypton");
		addName(Atoms.addStack(Atoms.RUBIDIUM), "Rubidium");
		addName(Atoms.addStack(Atoms.STRONTIUM), "Strontium");
		addName(Atoms.addStack(Atoms.YTTORIUM), "Yttorium");
		addName(Atoms.addStack(Atoms.ZIRCONIUM), "Zirconium");
		addName(Atoms.addStack(Atoms.NIOBIUM), "Niobium");
		addName(Atoms.addStack(Atoms.MOLYBDENUM), "Morybdenum");
		addName(Atoms.addStack(Atoms.TECHNETIUM), "Technetium");
		addName(Atoms.addStack(Atoms.RUTHENIUM), "Ruthenium");
		addName(Atoms.addStack(Atoms.RHODIUM), "Rhodium");
		addName(Atoms.addStack(Atoms.PALLADIUM), "Palladium");
		addName(Atoms.addStack(Atoms.SILVER), "Silver");
		addName(Atoms.addStack(Atoms.CADMIUM), "Cadmium");
		addName(Atoms.addStack(Atoms.INDIUM), "Indium");
		addName(Atoms.addStack(Atoms.TIN), "Tin");
		addName(Atoms.addStack(Atoms.ANTIMONY), "Antimony");
		addName(Atoms.addStack(Atoms.TELLURIUM), "Tellurium");
		addName(Atoms.addStack(Atoms.IODINE), "Iodine");
		addName(Atoms.addStack(Atoms.XENON), "Xenon");
		addName(Atoms.addStack(Atoms.CAESIUM), "Caesium");
		addName(Atoms.addStack(Atoms.BARIUM), "Barium");
		addName(Atoms.addStack(Atoms.LANTHANUM), "Lanthanum");
		addName(Atoms.addStack(Atoms.CERIUM), "Cerium");
		addName(Atoms.addStack(Atoms.PRASEODYMIUM), "Praseodymium");
		addName(Atoms.addStack(Atoms.NEODYMIUM), "Neodymium");
		addName(Atoms.addStack(Atoms.PROMETHIUM), "Promethium");
		addName(Atoms.addStack(Atoms.SAMARIUM), "Samarium");
		addName(Atoms.addStack(Atoms.EUROPIUM), "Europium");
		addName(Atoms.addStack(Atoms.GADOLINIUM), "Gadorinium");
		addName(Atoms.addStack(Atoms.TERBIUM), "Terbium");
		addName(Atoms.addStack(Atoms.DYSPROSIUM), "Dysprosium");
		addName(Atoms.addStack(Atoms.HOLMIUM), "Holimium");
		addName(Atoms.addStack(Atoms.ERBIUM), "Erbium");
		addName(Atoms.addStack(Atoms.THULIUM), "Thulium");
		addName(Atoms.addStack(Atoms.YTTERBIUM), "Ytterbium");
		addName(Atoms.addStack(Atoms.LUTETIUM), "Lutetium");
		addName(Atoms.addStack(Atoms.HAFNIUM), "Hafnium");
		addName(Atoms.addStack(Atoms.TANTALUM), "Tantalum");
		addName(Atoms.addStack(Atoms.TUNGSTEN), "Tungsten");
		addName(Atoms.addStack(Atoms.RHENIUM), "Rhenium");
		addName(Atoms.addStack(Atoms.OSMIUM), "Osmium");
		addName(Atoms.addStack(Atoms.IRIDIUM), "Iridium");
		addName(Atoms.addStack(Atoms.PLATINUM), "Platinum");
		addName(Atoms.addStack(Atoms.GOLD), "Gold");
		addName(Atoms.addStack(Atoms.MERCURY), "Mercury");
		addName(Atoms.addStack(Atoms.THALLIUM), "Thallium");
		addName(Atoms.addStack(Atoms.LEAD), "Lead");
		addName(Atoms.addStack(Atoms.BISMUTH), "Bismuth");
		addName(Atoms.addStack(Atoms.POLONIUM), "Polonium");
		addName(Atoms.addStack(Atoms.ASTATINE), "Astatine");
		addName(Atoms.addStack(Atoms.RADON), "Radon");
		addName(Atoms.addStack(Atoms.FRANCIUM), "Francium");
		addName(Atoms.addStack(Atoms.RADIUM), "Radium");
		addName(Atoms.addStack(Atoms.ACTINIUM), "Actinium");
		addName(Atoms.addStack(Atoms.THORIUM), "Thorium");
		addName(Atoms.addStack(Atoms.PROTACTINIUM), "Protactinium");
		addName(Atoms.addStack(Atoms.URANIUM), "Uranium");
		addName(Atoms.addStack(Atoms.NEPTUNIUM), "Neptunium");
		addName(Atoms.addStack(Atoms.PLUTONIUM), "Plutonium");
		addName(Atoms.addStack(Atoms.AMERICIUM), "Americium");
		addName(Atoms.addStack(Atoms.CURIUM), "Curium");
		addName(Atoms.addStack(Atoms.BERKELIUM), "Berkelium");
		addName(Atoms.addStack(Atoms.CALIFORNIUM), "Californium");
		addName(Atoms.addStack(Atoms.EINSTEINIUM), "Einsteinium");
		addName(Atoms.addStack(Atoms.FERMIUM), "Fermium");
		addName(Atoms.addStack(Atoms.MENDILEVIUM), "Mendilevium");
		addName(Atoms.addStack(Atoms.NOBELIUM), "Nobelium");
		addName(Atoms.addStack(Atoms.LAWRENCIUM), "Lawrencium");
		addName(Atoms.addStack(Atoms.RUTHERFORDIUM), "Rutherfordium");
		addName(Atoms.addStack(Atoms.DUBNIUM), "Dubnium");
		addName(Atoms.addStack(Atoms.SEABORGIUM), "Seaborgium");
		addName(Atoms.addStack(Atoms.BOHRIUM), "Bohrium");
		addName(Atoms.addStack(Atoms.HASSIUM), "Hassium");
		addName(Atoms.addStack(Atoms.MEITNERIUM), "Meitnerium");
		addName(Atoms.addStack(Atoms.DARMSTADTIUM), "Darmstadtium");
		addName(Atoms.addStack(Atoms.ROENTGENIUM), "Roentgenium");
		addName(Atoms.addStack(Atoms.COPERNICIUM), "Copernicium");
		addName(Atoms.addStack(Atoms.UNUNTRIUM), "UnunTrium");
		addName(Atoms.addStack(Atoms.FLEROVIUM), "Flerovium");
		addName(Atoms.addStack(Atoms.UNUNPENTIUM), "UnunPentium");
		addName(Atoms.addStack(Atoms.LIVERMORIUM), "Livermorium");
		addName(Atoms.addStack(Atoms.UNUNSEPTIUM), "UnunSeptium");
		addName(Atoms.addStack(Atoms.UNUNOCTIUM), "UnunOctium");
		
		addName(Atoms.addStack(Atoms.HYDROGEN), "ja_JP", "水素");
		addName(Atoms.addStack(Atoms.HELIUM), "ja_JP", "ヘリウム");
		addName(Atoms.addStack(Atoms.LITHIUM), "ja_JP", "リチウム");
		addName(Atoms.addStack(Atoms.BERYLLIUM), "ja_JP", "ベリリウム");
		addName(Atoms.addStack(Atoms.BORON), "ja_JP", "ホウ素");
		addName(Atoms.addStack(Atoms.CARBON), "ja_JP", "炭素");
		addName(Atoms.addStack(Atoms.NITROGEN), "ja_JP", "窒素");
		addName(Atoms.addStack(Atoms.OXYGEN), "ja_JP", "酸素");
		addName(Atoms.addStack(Atoms.FLUORINE), "ja_JP", "フッ素");
		addName(Atoms.addStack(Atoms.NEON), "ja_JP", "ネオン");
		addName(Atoms.addStack(Atoms.SODIUM), "ja_JP", "ナトリウム");
		addName(Atoms.addStack(Atoms.MAGNESIUM), "ja_JP", "マグネシウム");
		addName(Atoms.addStack(Atoms.ALMINIUM), "ja_JP", "アルミニウム");
		addName(Atoms.addStack(Atoms.SILICON), "ja_JP", "ケイ素");
		addName(Atoms.addStack(Atoms.PHOSPHORUS), "ja_JP", "リン");
		addName(Atoms.addStack(Atoms.SULFUR), "ja_JP", "硫黄");
		addName(Atoms.addStack(Atoms.CHLORINE),"ja_JP", "塩素");
		addName(Atoms.addStack(Atoms.ARGON),"ja_JP", "アルゴン");
		addName(Atoms.addStack(Atoms.POTASSIUM),"ja_JP","カリウム");
		addName(Atoms.addStack(Atoms.CALCIUM),"ja_JP","カルシウム");
		addName(Atoms.addStack(Atoms.SCANDIUM),"ja_JP","スカンジウム");
		addName(Atoms.addStack(Atoms.TITANIUM),"ja_JP","チタン");
		addName(Atoms.addStack(Atoms.VANADIUM),"ja_JP","バナジウム");
		addName(Atoms.addStack(Atoms.CHROMIUM),"ja_JP","クロム");
		addName(Atoms.addStack(Atoms.MANGANESE),"ja_JP","マンガン");
		addName(Atoms.addStack(Atoms.IRON),"ja_JP","鉄");
		addName(Atoms.addStack(Atoms.COBALT),"ja_JP","コバルト");
		addName(Atoms.addStack(Atoms.NICKEL),"ja_JP","ニッケル");
		addName(Atoms.addStack(Atoms.COPPER),"ja_JP","銅");
		addName(Atoms.addStack(Atoms.ZINC),"ja_JP","亜鉛");
		addName(Atoms.addStack(Atoms.GALLIUM),"ja_JP","ガリウム");
		addName(Atoms.addStack(Atoms.GERMANIUM),"ja_JP","ゲルマニウム");
		addName(Atoms.addStack(Atoms.ARSENIC),"ja_JP","ヒ素");
		addName(Atoms.addStack(Atoms.SELENIUM),"ja_JP","セレン");
		addName(Atoms.addStack(Atoms.BROMINE),"ja_JP","臭素");
		addName(Atoms.addStack(Atoms.KRYPTON),"ja_JP","クリプトン");
		addName(Atoms.addStack(Atoms.RUBIDIUM),"ja_JP","ルビジウム");
		addName(Atoms.addStack(Atoms.STRONTIUM),"ja_JP","ストロンジウム");
		addName(Atoms.addStack(Atoms.YTTORIUM),"ja_JP","イットリウム");
		addName(Atoms.addStack(Atoms.ZIRCONIUM),"ja_JP","ジルコニウム");
		addName(Atoms.addStack(Atoms.NIOBIUM),"ja_JP","ニオブ");
		addName(Atoms.addStack(Atoms.MOLYBDENUM),"ja_JP","モリブデン");
		addName(Atoms.addStack(Atoms.TECHNETIUM),"ja_JP","テクネチウム");
		addName(Atoms.addStack(Atoms.RUTHENIUM),"ja_JP","ルテニウム");
		addName(Atoms.addStack(Atoms.RHODIUM),"ja_JP","ロジウム");
		addName(Atoms.addStack(Atoms.PALLADIUM),"ja_JP","パラジウム");
		addName(Atoms.addStack(Atoms.SILVER),"ja_JP","銀");
		addName(Atoms.addStack(Atoms.CADMIUM),"ja_JP","カドニウム");
		addName(Atoms.addStack(Atoms.INDIUM),"ja_JP","インジウム");
		addName(Atoms.addStack(Atoms.TIN),"ja_JP","錫");
		addName(Atoms.addStack(Atoms.ANTIMONY),"ja_JP","アンチモン");
		addName(Atoms.addStack(Atoms.TELLURIUM),"ja_JP","テルル");
		addName(Atoms.addStack(Atoms.IODINE),"ja_JP","ヨウ素");
		addName(Atoms.addStack(Atoms.XENON),"ja_JP","キセノン");
		addName(Atoms.addStack(Atoms.CAESIUM),"ja_JP","セシウム");
		addName(Atoms.addStack(Atoms.BARIUM),"ja_JP","バリウム");
		addName(Atoms.addStack(Atoms.LANTHANUM),"ja_JP","ランダノイド");
		addName(Atoms.addStack(Atoms.CERIUM),"ja_JP","セリウム");
		addName(Atoms.addStack(Atoms.PRASEODYMIUM),"ja_JP","プラセオジム");
		addName(Atoms.addStack(Atoms.NEODYMIUM),"ja_JP","ネオジム");
		addName(Atoms.addStack(Atoms.PROMETHIUM),"ja_JP","プロメチウム");
		addName(Atoms.addStack(Atoms.SAMARIUM),"ja_JP","サマリウム");
		addName(Atoms.addStack(Atoms.EUROPIUM),"ja_JP","ユーロピウム");
		addName(Atoms.addStack(Atoms.GADOLINIUM),"ja_JP","ガドリニウム");
		addName(Atoms.addStack(Atoms.TERBIUM),"ja_JP","テルビウム");
		addName(Atoms.addStack(Atoms.DYSPROSIUM),"ja_JP","ジスプロジウム");
		addName(Atoms.addStack(Atoms.HOLMIUM),"ja_JP","ホルミニウム");
		addName(Atoms.addStack(Atoms.ERBIUM),"ja_JP","エルビウム");
		addName(Atoms.addStack(Atoms.THULIUM),"ja_JP","ツリウム");
		addName(Atoms.addStack(Atoms.YTTERBIUM),"ja_JP","イッテルビウム");
		addName(Atoms.addStack(Atoms.LUTETIUM),"ja_JP","ルテチウム");
		addName(Atoms.addStack(Atoms.HAFNIUM),"ja_JP","ハフニウム");
		addName(Atoms.addStack(Atoms.TANTALUM),"ja_JP","タンタル");
		addName(Atoms.addStack(Atoms.TUNGSTEN),"ja_JP","タングステン");
		addName(Atoms.addStack(Atoms.RHENIUM),"ja_JP","レニウム");
		addName(Atoms.addStack(Atoms.OSMIUM),"ja_JP","オスミウム");
		addName(Atoms.addStack(Atoms.IRIDIUM),"ja_JP","イリジウム");
		addName(Atoms.addStack(Atoms.PLATINUM),"ja_JP","白金");
		addName(Atoms.addStack(Atoms.GOLD),"ja_JP","金");
		addName(Atoms.addStack(Atoms.MERCURY),"ja_JP","水銀");
		addName(Atoms.addStack(Atoms.THALLIUM),"ja_JP","タリウム");
		addName(Atoms.addStack(Atoms.LEAD),"ja_JP","鉛");
		addName(Atoms.addStack(Atoms.BISMUTH),"ja_JP","ビスマス");
		addName(Atoms.addStack(Atoms.POLONIUM),"ja_JP","ポロニウム");
		addName(Atoms.addStack(Atoms.ASTATINE),"ja_JP","アスタチン");
		addName(Atoms.addStack(Atoms.RADON),"ja_JP","ラドン");
		addName(Atoms.addStack(Atoms.FRANCIUM),"ja_JP","フランシウム");
		addName(Atoms.addStack(Atoms.RADIUM),"ja_JP","ラジウム");
		addName(Atoms.addStack(Atoms.ACTINIUM),"ja_JP","アクチノイド");
		addName(Atoms.addStack(Atoms.THORIUM),"ja_JP","トリウム");
		addName(Atoms.addStack(Atoms.PROTACTINIUM),"ja_JP","プロアクチニウム");
		addName(Atoms.addStack(Atoms.URANIUM),"ja_JP","ウラン");
		addName(Atoms.addStack(Atoms.NEPTUNIUM),"ja_JP","ネプニウム");
		addName(Atoms.addStack(Atoms.PLUTONIUM),"ja_JP","プルトニウム");
		addName(Atoms.addStack(Atoms.AMERICIUM),"ja_JP","アメリシウム");
		addName(Atoms.addStack(Atoms.CURIUM),"ja_JP","キュリウム");
		addName(Atoms.addStack(Atoms.BERKELIUM),"ja_JP","バークリウム");
		addName(Atoms.addStack(Atoms.CALIFORNIUM),"ja_JP","カリホルニウム");
		addName(Atoms.addStack(Atoms.EINSTEINIUM),"ja_JP","アインスタイニウム");
		addName(Atoms.addStack(Atoms.FERMIUM),"ja_JP","フェルニウム");
		addName(Atoms.addStack(Atoms.MENDILEVIUM),"ja_JP","メンデレビウム");
		addName(Atoms.addStack(Atoms.NOBELIUM),"ja_JP","ノーベリウム");
		addName(Atoms.addStack(Atoms.LAWRENCIUM),"ja_JP","ローレンシウム");
		addName(Atoms.addStack(Atoms.RUTHERFORDIUM),"ja_JP","ラザフォージニウム");
		addName(Atoms.addStack(Atoms.DUBNIUM),"ja_JP","ドブニウム");
		addName(Atoms.addStack(Atoms.SEABORGIUM),"ja_JP","シーボルギウム");
		addName(Atoms.addStack(Atoms.BOHRIUM),"ja_JP","ボーリウム");
		addName(Atoms.addStack(Atoms.HASSIUM),"ja_JP","ハッシウム");
		addName(Atoms.addStack(Atoms.MEITNERIUM),"ja_JP","マイトネリウム");
		addName(Atoms.addStack(Atoms.DARMSTADTIUM),"ja_JP","ダームスタチウム");
		addName(Atoms.addStack(Atoms.ROENTGENIUM),"ja_JP","レントゲニウム");
		addName(Atoms.addStack(Atoms.COPERNICIUM),"ja_JP","コペルニシウム");
		addName(Atoms.addStack(Atoms.UNUNTRIUM),"ja_JP","ウンウントリウム");
		addName(Atoms.addStack(Atoms.FLEROVIUM),"ja_JP","フレロビウム");
		addName(Atoms.addStack(Atoms.UNUNPENTIUM),"ja_JP","ウンウンペンチウム");
		addName(Atoms.addStack(Atoms.LIVERMORIUM),"ja_JP","リバモリウム");
		addName(Atoms.addStack(Atoms.UNUNSEPTIUM),"ja_JP","ウンウンセプリウム");
		addName(Atoms.addStack(Atoms.UNUNOCTIUM),"ja_JP","ウンウンオクチウム");
		
		
		addName(KagacraftItems.testTube, "Test Tube");
		addName(KagacraftItems.spiritLamp, "Spirit Lamp");
		addName(new ItemStack(KagacraftItems.electrolysers, 1, 0), "Electrolysers");
		addName(new ItemStack(KagacraftItems.electrolysers, 1, 1), "Decomposer");
		addName(new ItemStack(KagacraftItems.electrolysers, 1, 2), "Synthesis");
		addName(new ItemStack(KagacraftItems.electrolysers, 1, 3), "Hydrogen Generator");
		
		ModLoader.addLocalization("itemGroup.Kagacraft", "Kagacraft Items");
	}
	
	public static void addName(Object objectToName, String lang, String name)
	{
		LanguageRegistry.instance().addNameForObject(objectToName, lang, name);
	}
	
	public static void addName(Object objectToName, String name)
	{
		LanguageRegistry.instance().addName(objectToName, name);
	}
}
